cmake_minimum_required(VERSION 4.1)
project(TAD_Vector_Dinamic_SDA)

set(CMAKE_CXX_STANDARD 20)
add_executable(TAD_Vector_Dinamic_SDA
        "Proiect C++/App.cpp"
        "Proiect C++/VectorDinamic.cpp"
        "Proiect C++/IteratorVectorDinamic.cpp"
        "Teste/TestScurt.cpp"
        "Teste/TestExtins.cpp"
)